### ISSUE TITLE
ComID fields should be primary keys

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#10]
The spatial tables (nhdarea, nhdflowline, nhdline, nhdpoint, nhdwaterbody) have a ComID field.  This should be used as the primary key.

**Comment by ischneider** [comment]
So drop the gid primary key and change primary key to ComID?

Are you thinking we just do this manually in the sql dumps or automate the process?

**Comment by ischneider** [comment]
I fixed this in the data base and a script exists to do it again if needed. As long as re dump/restore from the existing data, this will work.
