### ISSUE TITLE
add uploader form

### ISSUE THREAD

**Issue by bartvde** [planetfederal/usgs#100]

**Comment by bartvde** [comment]
This should be done, can be tested once a new version of the client app is the deployed on the demo server.

**Comment by tschaub** [comment]
Thinking about it some more, I think it's ok if the client side change stays in while we still don't have the extension on the server.  We have an additional demo to give on Aug 30 - and I want things to be stable on that day at least.  But I can log in before the demo and avoid the authentication challenge during.
