### ISSUE TITLE
avoid prompt for credentials on add layer

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#106]
At some point, the application started prompting for credentials when we launch the add layers dialog.  Need to dig in a bit to see what changed.

**Comment by bartvde** [comment]
Tim, ultimately would you want this application to have a Login button just like GeoExplorer?

**Comment by bartvde** [comment]
The above mentioned commit was reverted since it caused side effects.

**Comment by bartvde** [comment]
I've disabled the upload for now.

**Comment by tschaub** [comment]
Lets call this one invalid.  If we add upload, then we'll deal with it.  I just tried pulling in the upload module from the Suite and it doesn't run with the GeoServer trunk.
