### ISSUE TITLE
modified flowline not available for snapping

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#110]
If you insert a new flowline, the newly inserted feature is immediately available for snapping.  If you then modify that feature and save, the modified feature is not available for snapping.

**Comment by bartvde** [comment]
This seems to be caused by the "query" listener of feature manager in index.html

**Comment by bartvde** [comment]
Basically, on inserts, we need to clear the filter on the snapping agent.

**Comment by bartvde** [comment]
Hmm this is more tricky than I thought it was ...
