### ISSUE TITLE
remove selected features when exception queue is closed

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#114]
Currently, there is no way to get rid of selected features that result from zooming to an exception.  I think it would make sense to get rid of these features when the exception queue is closed.  Ideally, selected features would also disappear when an exception has been corrected as well (even if the exception queue is still open).

**Comment by bartvde** [comment]
I am having trouble adding listener to either the grid or the containing window, nothing seems to work, beforeclose, before hide, before destroy etc.

**Comment by bartvde** [comment]
Not sure what I was doing wrong but at least beforehide is now working fine.

**Comment by bartvde** [comment]
Hmm, it works the first time, but after that not anymore ....

**Comment by bartvde** [comment]
The part in the ticket description after ideally has already been implemented I believe. The viewer's feartureedit event reloads the store on the grid, so that should be okay to deal with this.
