### ISSUE TITLE
add FType and FCode dictionaries for new layers

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#116]
With the latest spreadsheets in the USGS docs folder, we should be able to add FType descriptions for a few of the new layers.  Same with FCode.  Not all of the new layers have FType/FCode fields (and one is annoyingly FTYPE/FCODE).  Focus first on those that do.

**Comment by bartvde** [comment]
Trans_AirportRunway only has FCODE.
Trans_RailFeature only has FCode.

So what to do with these? Determine FType from the FCode value?

**Comment by bartvde** [comment]
I've added the dictionaries, and made the lookup for FCode and FType fields case insensitive. Leaving this ticket open for the question above.

**Comment by tschaub** [comment]
Remaining part of this was addressed in 766167b809ae33e96f13fa2bf7948060f276a71e.
