### ISSUE TITLE
AttributeForm does not initialize date fields properly

### ISSUE THREAD

**Issue by ahocevar** [planetfederal/usgs#16]
Date fields initially get an empty value. As long as they do, we need a workaround in FeatureEditWizard::updateFeature. But this workaround makes impossible to clear values of other fields.

**Comment by ahocevar** [comment]
The workaround does not have any impact on FeatureEditWizard::updateFeature any more, but the issue still needs to be addressed.

**Comment by bartvde** [comment]
Should be done now. Closing.
