### ISSUE TITLE
allow configuration of geometry type

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#19]
With the data exported directly from the gdb, GeoServer advertises just "Geometry" as the type (for the "Shape") field.  When modifying an existing flowline feature, we don't cast to a MultiLineString and Postgres rejects the update because '"NHDFlowline" violates check constraint "enforce_geotype_Shape"'.

We should see if we can get a more specific geometry type advertised.  Until then, we should be able to configure the application with the additional type information.

**Comment by ahocevar** [comment]
As far as I remember, manually changing the geometry_columns table should result in GeoServer advertising the geometry type specified there.

**Comment by ahocevar** [comment]
Application and gxp level changes in with 977ca43e788f58cd24434ad893fc10fd63583944; Will be fixed when http://trac.osgeo.org/openlayers/ticket/3407 is in.

**Comment by bartvde** [comment]
I think we can close this one. Andreas has finished all the work in OL for this if we ever need it again on the client-side.
