### ISSUE TITLE
update feature edit wizard to match design

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#23]
Where possible, the feature edit wizard should match the wireframes on the [design page](https://github.com/opengeo/usgs/wiki/Design).

**Comment by bartvde** [comment]
This was mostly done, there may be some tweaks here and there, such as only enable the Delete button if a commit message has been typed or a previous metadata entry has been opened, but I would suggest opening up specific tickets for those.

Also, the design is missing what the Find existing metadata records window should look like.

I implemented that as a button though, not sure what it's supposed to be in Rollie's design?
