### ISSUE TITLE
populate metadata form with previous record values

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#28]
After a metadata record has been created or selected, the values should show up in the feature edit wizard on subsequent edits.  For example, if I launch the app for the first time, make an edit, and write "test insert" for the first commit message, on my next edit this same message should be visible in the metadata panel, and I should be able to save without hitting "next" to see the metadata.

**Comment by bartvde** [comment]
Since the gxp FeatureEditor creates a new popup all the time, we cannot store the state there. So we need to find an alternative place to store the state.

**Comment by bartvde** [comment]
A first step will be to get the MetadataForm to have a record (so retrieve it after save) all the time, for both open and save.

**Comment by bartvde** [comment]
I am closing this one, but will open up a new issue for the empty transaction.
