### ISSUE TITLE
close editor wizard on cancel 

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#30]
If the user clicks "cancel" on the editor wizard and then confirms that they do not want to save changes, the editor wizard should close.  Currently, it stays open.

**Comment by tschaub** [comment]
Looks like this is an unhandled error trying to call `removeFeatures` on a `null` layer.  Haven't looked more closely.  But the workflow is launch app, activate NHDPoint for editing, insert new feature, click next, click cancel (before save).

**Comment by bartvde** [comment]
I can reproduce this issue. this.layer is null in ModifyFeature.js line 386
