### ISSUE TITLE
allow recovery from failed edit

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#45]
User adds a new waterfall feature that doesn't intersect an existing stream.  User enters new metadata and tries to save feature.  User sees a nicely formatted exception report and has the option to continue editing the same feature or to queue the issue.  User chooses to continue editing, snaps the waterfall to an existing stream, and successfully saves the feature (without having to add another metadata record).

**Comment by bartvde** [comment]
This is hard to test right now because of the double encoding of the exceptions, will have to revisit later.

**Comment by tschaub** [comment]
You should currently be getting back an exception with the locator "js:intersects".  Though the exception body is bad, you could just display something simple like "js:intersects failed" to the user.  Then you could still let the user continue editing and try to resubmit the transaction again.  The important part at this point is getting the workflow down.  We can solve the exception message formatting later.

**Comment by tschaub** [comment]
Exception messages should be in better shape after 02446e801449d3ef8c7c73b140e250a9f60b5af3.  Will confirm.

**Comment by tschaub** [comment]
Yeah, posting a waterfall point that doesn't intersect a stream:

```
<ows:ExceptionReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ows="http://www.opengis.net/ows" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/ows http://usgs.demo.opengeo.org:8080/geoserver/schemas/ows/1.0.0/owsExceptionReport.xsd">
    <ows:Exception exceptionCode="NoApplicableCode" locator="js:intersects">
        <ows:ExceptionText>{"message":"Intersection Test Failed","rule":{"name":"intersects","subjectLayer":"nhdpoint","subjectFType":487,"objectLayer":"nhdflowline"}}</ows:ExceptionText>
    </ows:Exception>
</ows:ExceptionReport>
```

**Comment by bartvde** [comment]
I can confirm that this workflow is now supported.

**Comment by ahocevar** [comment]
Looking at https://github.com/opengeo/usgs/wiki/Prototype-Demo-I, I think it would be better to have an option to return to the original popup where attributes can also be added. It is now possible to e.g. snap the waterfall point to a flowline, but it's not possible to change any attributes.
