### ISSUE TITLE
allow user to queue exceptions

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#46]
When the exception report includes an exception with a locator that has a "js:" prefix, the user should be able to queue this exception.  Clicking on a "queue this exception for later" checkbox should allow the user to click "save" again immediately.

A transaction that is intended to queue exceptions should have a `<Native>` element with JSON that includes a member corresponding to the locator attribute in the initial exception.  The value of this member should be an object with a "queue" member whose value is `true`.  For example:

```
{
    "js:intersects": {"queue": true}
}
```

This choice (to queue exceptions) should only persist for this single transaction.

**Comment by bartvde** [comment]
This is already implemented in ExceptionPanel, there is a "queue" writer and the beforewrite listener has single true so will only work on the single transaction.

**Comment by tschaub** [comment]
I may have broken this behavior with changes to the exception message structure (see #56).  Currently, if I insert a waterfall off of a flowline, I see a generic exception form (with Message, Locator, and Exception code fields), but to a way to queue the exception or a clear indication of how to recover.
