### ISSUE TITLE
reflect application state in hash

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#47]
At a minimum, it would be nice to have the map center and zoom updated in the URL anchor.  In addition, it would make sense to include the metadata record id there.  This would allow the user to bookmark the application and restore the most important parts of the state.

**Comment by tschaub** [comment]
Thanks for the work on this.  I see the anchor being updated with changes in the application, but I think restoring the state is still not working as expected.

For example, this URL http://usgs.demo.opengeo.org/usgs/#zoom=18&lat=5036940.4962&lon=-12152419.80901&layers=TFFFFFFFTTFTF&metadata=nhdmetadata.523 should bring me back to zoom level 18 with metadata record 523 selected.  When I load the application with that URL, I get taken to the full extent (zoom level 6).  I do see the same metadata record loaded when I edit again.  And the proper layers are visible.  So it seems like it is just the map set center sequence that needs work.

**Comment by ahocevar** [comment]
The ArgParser control is missing, and the initial state is set too early.

**Comment by ahocevar** [comment]
But I think I'm not going to use the Permalink/ArgParser control combo.
