### ISSUE TITLE
add some scale dependent styling

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#48]
The point icons, at a minimum, should be resized at low zoom levels.  It would also make sense to reduce the stroke width of the lines and polygons.

**Comment by bartvde** [comment]
Hmm, wishing SLD had something like Mapserver's SYMBOLSCALE, a scale at which symbols should be drawn at the defined size, and a maxsize and minsize range to scale in between.

http://docs.geoserver.org/latest/en/user/styling/sld-cookbook/points.html#zoom-based-point

**Comment by bartvde** [comment]
The other layers have really tiny outlines, so they should not be an issue. Only exception is BayInlet in NHDArea.

**Comment by bartvde** [comment]
This could have probably helped as well:

http://docs.geoserver.org/stable/en/user/styling/sld-extensions/substitution.html
