### ISSUE TITLE
force redraw on edit

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#49]
We may be doing this already, but I'm not seeing newly inserted features shown up on the WMS layers.  It could be a GWC issue.  To reproduce, zoom all the way in, find a stream, and add a waterfall snapped to the stream.  I see a successful insert, but I don't see the feature until I zoom back out.

**Comment by bartvde** [comment]
I debugged the issue, and concluded that redrawMatchingLayers is getting called in gxp's FeatureManager, and that the correct WMS layer is getting a redraw call with force true. So the client is doing everything it can AFAICT.

So I am guessing GWC issue here.

**Comment by bartvde** [comment]
Confirmed that this is now working. Was fixed by Gabriel.
