### ISSUE TITLE
check status of queues at the end of every transaction

### ISSUE THREAD

**Issue by bartvde** [planetfederal/usgs#5]

**Comment by bartvde** [comment]
This will need to be done by calling a WPS process directly?

**Comment by bartvde** [comment]
We need some more info on the server-side of things here before we can actually implement this on the client-side.

**Comment by tschaub** [comment]
Repurposing this ticket for the server side handling of exceptions that are no longer pertinent.

**Comment by tschaub** [comment]
Calling this one good for 0.8.
