### ISSUE TITLE
point sticks to mouse on first modification

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#50]
Activate the modify tool, click on an existing feature, move the attribute dialog, and drag the feature.  I see the feature stick to the cursor instead of stopping on mouseup.  Subsequent drags work as expected.

**Comment by ahocevar** [comment]
This is an OpenLayers issue: http://trac.osgeo.org/openlayers/ticket/3428.

**Comment by ahocevar** [comment]
This was a tough one. http://trac.osgeo.org/openlayers/ticket/3428 is ready for review.

**Comment by ahocevar** [comment]
Thanks @jorix for an OpenLayers fix that was better than mine.
