### ISSUE TITLE
collect features post insert

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#54]
GeoServer doesn't fire the POST_INSERT event after a transaction that contains inserts.  We either need to work around this issue or patch GeoServer to fire this event.  Additional detail here: http://irc.opengeo.org/log/2011/07/27/#T10:11:31Z

**Comment by ahocevar** [comment]
Created https://jira.codehaus.org/browse/GEOS-4691, with a patch that contains groldan's patch and my tests.
