### ISSUE TITLE
featureid values in nhdexceptions table are invalid 

### ISSUE THREAD

**Issue by ahocevar** [planetfederal/usgs#57]
The feature ids are temporary ones, like fid-66af5066_1316e31a07a_-7fdb

**Comment by tschaub** [comment]
This should be fixed in our GeoServer build with e8095541941e89d8d8606fb2041128f675944193 and in the WFS hook with 6fe65a0abff257b8f3225e0b560446a9bb6cc70a.  Confirmed on the demo server that legit ids are getting added to the exception table.  Thanks for the GeoServer fix @ahocevar and @groldan.
