### ISSUE TITLE
Show queue of exceptions in the map

### ISSUE THREAD

**Issue by bartvde** [planetfederal/usgs#6]
Maybe by using some kind of SLD?

**Comment by tschaub** [comment]
I think this can be done one feature at a time for now.  At a minimum, the list of exceptions (simple data view or grid) should have a "zoom to feature" button.  The exception records have namespace, featuretype (unqualified), and featureid fields.  This should be enough to either issue a WFS GetFeature and zoom to the feature extent.  Perhaps it would be easiest to have another feature manager that just maintained the feature associated with the selected exception.

**Comment by bartvde** [comment]
Okay, this should be enough info to get started, so this means changing the structure of the current exception tables.

**Comment by bartvde** [comment]
I temporarily changed the NHDExceptions table on the db server to accomplish this:

alter table "NHDExceptions" add column namespace varchar(255);
alter table "NHDExceptions" add column featuretype varchar(255);

and added one dummy row for testing:

insert into "NHDExceptions" values(1, 'nhdmetadata.65', 'nhdpoint.16308', 'js:intersects', 'exception msg goes here', 'http://www.usgs.gov/', 'nhdpoint');

**Comment by tschaub** [comment]
Thanks Bart.  I updated the [data page](https://github.com/opengeo/usgs/wiki/Data) yesterday with a similar schema for exceptions.  This is in the usgs_full db now, but I need to do a dump before renaming to usgs.

**Comment by bartvde** [comment]
Initial version should be done.
