### ISSUE TITLE
improve metadata form

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#66]
This is lower priority, but if possible, it would be nice to have the metadata entry form cleaned up a bit.  The optional fields displayed should have more readable titles.  And it looks like fields should have anchor 95% or similar to avoid running into the scrollbar.  Finally, wherever possible, it would be good to populate date fields with the current date.

**Comment by ahocevar** [comment]
Is there a document that points out which fields are to be displayed, and what labels to use?
