### ISSUE TITLE
rework handling of known exception types

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#70]
Exception reports now look something like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/ows http://localhost:8080/geoserver/schemas/ows/1.0.0/owsExceptionReport.xsd">
    <ows:Exception exceptionCode="7" locator="js:MustNotCross">
        <ows:ExceptionText>{"code":"7","process":"js:MustNotCross","subjectLayer":"nhdflowline","subjectFType":460,"objects":[{"layer":"nhdwaterbody","ftypes":[390]}],"autoCorrectable":true}</ows:ExceptionText>
    </ows:Exception>
</ows:ExceptionReport>
```

The `exceptionCode` attribute identifies the specific rule that was violated (these codes come from the [rules doc](https://spreadsheets.google.com/a/opengeo.org/spreadsheet/ccc?key=0Ag1yfGJbP0RjdEZNVm5IRHNXeGk1TkpoMjdrdUd3M0E&hl=en_US)).  In most cases, the client doesn't care about the specific rule code.  The only time the client needs to worry about the specific code is when additional data is needed to correct the rule (as opposed to auto-correcting the exception without additional data or queuing the exception).

The `locator` attribute corresponds to the process used by a particular rule.  The client should be able to render an exception message by using a template keyed by this locator.  All known exception types are expected to have messages that parse as JSON.  When rendering an exception message, the client should confirm that the JSON parses.

If the exception message parses to an object with a truthy `autoCorrectable` member, the client can ask the server to auto-correct the exception.  This would be accomplished by including a `Native` element with a member corresponding to the rule code:

```
{"7": {"autoCorrect": true}}
```

If the exception message parses to an object without an `autoCorrectable` member (or a falsey value), the client can ask the server to queue the exception.  This is accomplished by including a `Native` element that includes something like this:

```
{"7": {"queue": true"}}
```

For special case rules that require additional user input for auto-correction, the `autoCorrect` member serialized in the `Native` element should be an object (ticket for this elsewhere).

**Comment by tschaub** [comment]
Actually, let's sync up on this first.

**Comment by ahocevar** [comment]
In addition to the above commit, 4073738cc43ae9012dc0b27febe91bfd5b8000e2 implements the autoCorrect part
