### ISSUE TITLE
GWC integration broken on demo server

### ISSUE THREAD

**Issue by ahocevar** [planetfederal/usgs#76]
This is low priority, but I'm creating this ticket so we don't forget about it.

http://usgs.demo.opengeo.org/geoserver/wms?SERVICE=WMS&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=TRUE&LAYERS=usgs%3Anhdwaterbody&VERSION=1.1.1&REQUEST=GetMap&TILED=true&SRS=EPSG%3A900913&BBOX=-11584184.509062,5009377.085,-11271098.44125,5322463.1528125&WIDTH=256&HEIGHT=256 is served by GeoServer, whereas the same request from the gwc/service/wms endpoint is served by GWC just fine:
http://usgs.demo.opengeo.org/geoserver/gwc/service/wms?SERVICE=WMS&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=TRUE&LAYERS=usgs%3Anhdwaterbody&VERSION=1.1.1&REQUEST=GetMap&TILED=true&SRS=EPSG%3A900913&BBOX=-11584184.509062,5009377.085,-11271098.44125,5322463.1528125&WIDTH=256&HEIGHT=256

Note: we know that a tile is served by GWC when we get a geowebcache-tile-index response header.

Another issue is that I don't see any cache headers set for tiles served by GWC (not even with the latter request).

**Comment by tschaub** [comment]
Request directly through GeoServer:

```
curl -is -D - 'http://usgs.demo.opengeo.org/geoserver/wms?SERVICE=WMS&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=TRUE&LAYERS=usgs%3Anhdwaterbody&VERSION=1.1.1&REQUEST=GetMap&TILED=true&SRS=EPSG%3A900913&BBOX=-11584184.509062,5009377.085,-11271098.44125,5322463.1528125&WIDTH=256&HEIGHT=256' -o /dev/null
```

And the response (no headers from GWC):

```
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Disposition: inline; filename=usgs-nhdwaterbody.png
Content-Type: image/png
Date: Tue, 02 Aug 2011 14:36:31 GMT
Connection: close
Transfer-Encoding: chunked
```

Request for same image through GWC:

```
curl -is -D - 'http://usgs.demo.opengeo.org/geoserver/gwc/service/wms?SERVICE=WMS&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=TRUE&LAYERS=usgs%3Anhdwaterbody&VERSION=1.1.1&REQUEST=GetMap&TILED=true&SRS=EPSG%3A900913&BBOX=-11584184.509062,5009377.085,-11271098.44125,5322463.1528125&WIDTH=256&HEIGHT=256' -o /dev/null
```

And the response (with `geowebcache-tile-index` header from GWC):

```
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
geowebcache-tile-index: [27, 80, 7]
Content-Type: image/png
Content-Length: 9018
Date: Tue, 02 Aug 2011 14:38:14 GMT
Connection: close
```

If indeed we aren't getting any cached images from GWC, I think this is a high priority to at least investigate.

**Comment by tschaub** [comment]
This looks to have been fixed by a [GeoServer change](https://github.com/opengeo/geoserver/commit/9e210962e6ff0218ca5c6da26ca9671a3824d072).  Pulled in with 5a8d45cd42e5a5786a5932e5d3a0008c08965d45.
