### ISSUE TITLE
create dump of clean NHD data for restoring

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#8]
We need a convenient way to restore the NHD data to its pristine state.

**Comment by ischneider** [comment]
dump from/restore to the usgs database on db.demo.openge.org ?
is there a need to dump/restore specific tables or all?

**Comment by tschaub** [comment]
All tables in usgs database on db.demo.opengeo.org.

**Comment by tschaub** [comment]
At this point, I _think_ we need a fresh usgs_full db - created as described on the [data](https://github.com/opengeo/usgs/wiki/Data) page.  This should be done with an updated post_process.sql from the repo (`git pull` first).

To be complete, this should result in a usgs_full.dump on the db.demo.opengeo.org machine that we can use to restore (with something like `pg_restore -c -U opengeo -d usgs -f usgs_full.dump`.  This may already be complete.

**Comment by ischneider** [comment]
I've updated https://github.com/opengeo/usgs/wiki/Data with details. The current `usgs` db is a template copy of `usgs_full`.
