### ISSUE TITLE
store application preferences in metadata report

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#81]
It would be really slick to have application preferences persist on reload.  It makes sense to have application preferences associated with a metadata record (e.g. when editing a batch of pipelines, you might create one metadata record and one set of editing preferences).  In the short-term, we could use an existing metadata attribute that is not being used by the application.  The "CompetenessReport" attribute is a fine candidate.

If time allows, it would be great to try to parse (as JSON) the application preferences from the metadata record.  When preferences change, the record should be updated.

**Comment by tschaub** [comment]
Improving the metadata form (#66) should accompany this change (as the user should not be able to edit the "CompletenessReport" among other things).

**Comment by ahocevar** [comment]
Looks like the MetadataForm needs some serious refactoring - I notice very odd behavior with its store, and some strange beforeWrite events.

**Comment by bartvde** [comment]
The record has the correct information (so CompletenessReport is set) however the feature only has the initial attributes (MetadataDate and ProcessDescription). That's probably why we end up with an empty transaction.

**Comment by bartvde** [comment]
the weird thing is that the debugger never reaches FeatureStore::onUpdate
