### ISSUE TITLE
preferences panel should use rule specific form items with rule title

### ISSUE THREAD

**Issue by ahocevar** [planetfederal/usgs#83]
The rule specific form items currently stored in the ExceptionPanel should go to a place where they can be accessed by other components as well. The Preferences panel should use them to render all the preferences.

The server should return a title in addition to the rule code (`"code": 6, "title": "Vertical Relationship"...`). The title should be used as fieldset title for every rule specific preference.

**Comment by tschaub** [comment]
Title added to auto-correctable rules in b0a0b551d6cdbcc77fa502747432c1512b66261f.
