### ISSUE TITLE
update exception queue after transactions

### ISSUE THREAD

**Issue by ahocevar** [planetfederal/usgs#86]
To make sure that we see an up-to-date list of exceptions, the client needs to reload the queue not only when opening the exception queue grid, but also when it is open.

**Comment by tschaub** [comment]
See also #91.  A feature displayed when zooming to an exception can be orphaned on the layer if you try to delete it.  If possible, I think it would make sense to address #91 before reloading of the queue while the grid is open.  (Though it would be a nice first enhancement to reload the exceptions when opening the queue grid.)

**Comment by tschaub** [comment]
Actually, it looks to me like the exceptions are already reloaded when the grid is rendered.  So maybe the first part of this is already addressed.
