### ISSUE TITLE
clicking on a feature with the wizard open causes trouble

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#87]
This is _not_ worth spending time on with other 0.8 tickets open.  I'm just opening it so we don't forget about it.  This could be a [gxp issue](https://github.com/opengeo/gxp/issues/68), or it could be unique to the FeatureEditWizard.  If you click on another feature with the wizard open, you can see unhandled errors.  One of the feature removal listeners is removing features.

**Comment by bartvde** [comment]
This should not be an issue any more since now when an editing popup is open, the select control will not be active.
