### ISSUE TITLE
allow queuing of multiple exceptions in a single transaction

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#90]
Doesn't need to be in 0.8, but eventually we should allow the user to queue more than one exception in a single transaction.  The queue settings should still not be stored in app preferences, but they should be compiled for a single edit.

An example workflow would be to create a pipeline that crosses a stream (but doesn't intersect the endpoint of any other flowline or a sink/rise).  The user would first be prompted to specify the vertical relationship.  After trying to save again, they would be prompted to queue the exception about touching at least one feature.  After another save, they would be prompted to queue the exception about intersecting a flowline endpoint or sink/rise.  The final transaction would include something like this:

```
{
    "6": {
        "autoCorrect": {
            "relationship": "over"
        }
    },
    "15": {
        "queue": true
    },
    "16": {
        "queue": true
    }
}
```

**Comment by bartvde** [comment]
Hey Tim, I am not sure I am getting this one, currently the final transaction includes:

<wfs:Native vendorId="usgs" safeToIgnore="true">{"6":{"title":"Pipeline Vertical Relationship","autoCorrect":{"relationship":"over"}},"16":{"title":"Split Flowline","autoCorrect":true},"15":{"queue":true}}/wfs:Native

so what is missing here at the moment? Can you clarify?

**Comment by bartvde** [comment]
I can see the difference is one autoCorrect and one queue, however it seems the autoCorrect succeeds so I don't have a chance to queue 16?

**Comment by tschaub** [comment]
There is currently an issue on the server side that is making this harder to see.  If you create a new flowline that doesn't touch any other flowlines, the first exception is code 11.  If you queue this exception, you hit code 16.  Currently, 16 says it is auto-correctable.  It shouldn't (because you have chosen queued 11).  Ignoring that, you can still see that when you choose to auto-correct 16, the transaction is issued without saying to queue 11.

As long as the feature edit wizard is open, choices to queue exceptions should be cumulative.  So if the user chooses to queue 11 and then hits 16, when you make a choice about 16, the transaction should still say to queue 11.

**Comment by tschaub** [comment]
I'll try to address the server side issue to make this clearer.  But the bottom line is that the client should be able to issue a transaction that includes instructions to queue more than one exception type (not just auto-correct one and queue one).

**Comment by bartvde** [comment]
Thanks for the clarification Tim, it is now much more clear to me.
