### ISSUE TITLE
avoid duplicate display of features in exception queue

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#91]
If the user opens the exception queue and zooms to a feature, the feature is rendered client side (very useful).  If the user then selects the feature for modification, the feature is rendered a second time (with select intent).  At this point, if the user deletes the feature, the one with the select intent is removed, but the original is still rendered.

**Comment by ahocevar** [comment]
Appears to work now as expected.

**Comment by tschaub** [comment]
Uh oh.  I'm seeing orphaned features again.  I'll try to figure out a reproducible workflow.  This is not critical for the demo.

**Comment by tschaub** [comment]
Yikes, scratch that.  Too late.

**Comment by tschaub** [comment]
Ok, I'll quit commenting on this now.  Suffice it to say there is something odd going on.  I can now see a ton of features rendered client side.
