### ISSUE TITLE
deleting vertices doesn't result in an update

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#96]
This is likely an issue with the ModifyFeature control, but I'm not investigating it now.  If you select an existing feature and use delete to remove vertices, when you save the change (with no other changes, just deleted vertices), the geometry doesn't get passed in the update.

**Comment by bartvde** [comment]
Right, I am able to reproduce this one. Looking into this.

**Comment by bartvde** [comment]
Indeed an issue in OpenLayers ModifyFeature Control, in setFeatureState this.modified is false but should be true of course in this case. I've opened up:

http://trac.osgeo.org/openlayers/ticket/3463
