### ISSUE TITLE
add filter to snapping target to avoid snapping to self

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#97]
The snapping target should be updated with a filter that excludes the currently editable feature (when from the same feature type).  This would make it so you can adjust vertices of a feature without having them snap to edges/vertices of the same feature.

**Comment by bartvde** [comment]
Looking into this now, but there seems to be a bug in OpenLayers.Control.Snapping, evaluate should use the feature as the argument and not feature.attributes.

**Comment by bartvde** [comment]
http://trac.osgeo.org/openlayers/ticket/3468

**Comment by bartvde** [comment]
Okay so this should work when the OL patch gets in.
